import React, { forwardRef } from "react";
import ThreeDotsSvg from "@/assets/icons/three-dots.svg";
import SettingSunSvg from "@/assets/icons/setting-sun-icon.svg";
import PlannedSvg from "@/assets/icons/planned-icon.svg";
import Calendar2Svg from "@/assets/icons/calendar-2.svg";
import CompletedSvg from "@/assets/icons/completed-icon.svg";
import TrashSvg from "@/assets/icons/trash-icon.svg";
import SuitcaseSvg from "@/assets/icons/suitcase-icon.svg";
import SuitcaseFillSvg from "@/assets/icons/suitcase-icon-fill.svg";
import PaperPlusSvg from "@/assets/icons/paper-plus-icon.svg";
import TagSvg from "@/assets/icons/tag-icon.svg";
import TagFillSvg from "@/assets/icons/tag-icon-fill.svg";
import AddModalSvg from "@/assets/icons/add-modal.svg";
import CheckSvg from "@/assets/icons/check-icon.svg";
import XSvg from "@/assets/icons/x-icon.svg";
import ArrowLeftSvg from "@/assets/icons/arrow-left.svg";
import SettingsWhiteSvg from "@/assets/icons/settings-white.svg";
import NotificationSvg from "@/assets/icons/notification.svg";
import TimerCircleSvg from "@/assets/icons/timer-circle.svg";
import CalendarSvg from "@/assets/icons/calendar.svg";
import FlagSvg from "@/assets/icons/flag-icon.svg";
import PomodoroSvg from "@/assets/icons/pomodoro.svg";
import RepeatSvg from "@/assets/icons/repeat.svg";
import ArrowRightSvg from "@/assets/icons/arrow-right-icon.svg";
import InfinitySvg from "@/assets/icons/infinity-icon.svg";
import CircleEmptySvg from "@/assets/icons/circle-empty-icon.svg";
import CircleCheckmarkSvg from "@/assets/icons/circle-checkmark.svg";
import HourGlassSvg from "@/assets/icons/hourglass-icon.svg";
import GoogleSvg from "@/assets/icons/google.svg";
import FacebookSvg from "@/assets/icons/facebook.svg";
import EyeOffSvg from "@/assets/icons/eye-off.svg";
import EyeSvg from "@/assets/icons/eye.svg";
import EmailSvg from "@/assets/icons/email.svg";
import DangerCircleSvg from "@/assets/icons/danger-circle-icon.svg";
import CancelSvg from "@/assets/icons/cancel-icon.svg";
import CalendarFillSvg from "@/assets/icons/calendar-fill.svg";
import ArrowRightVectorSvg from "@/assets/icons/arrow-right-vector.svg";
import ArrowDownSvg from "@/assets/icons/arrow-down.svg";
import AppleSvg from "@/assets/icons/apple.svg";
import PlusSvg from "@/assets/icons/plus-icon.svg";
import FileUploadSvg from "@/assets/icons/file-upload.svg";
import FileSvg from "@/assets/icons/file.svg";

// Wrapper function to allow all props (className, onClick, etc.)
// Wrapper function with displayName and full SVGProps support
const IconWrapper = (SvgComponent: React.FC<React.SVGProps<SVGSVGElement>>) => {
  const WrappedIcon = forwardRef<SVGSVGElement, React.SVGProps<SVGSVGElement>>(
    (props, ref) => <SvgComponent ref={ref} {...props} />
  );

  WrappedIcon.displayName = SvgComponent.name || "Icon";
  return WrappedIcon;
};

export const ThreeDotsIcon = IconWrapper(ThreeDotsSvg);
export const SettingSunIcon = IconWrapper(SettingSunSvg);
export const PlannedIcon = IconWrapper(PlannedSvg);
export const Calendar2Icon = IconWrapper(Calendar2Svg);
export const CompletedIcon = IconWrapper(CompletedSvg);
export const TrashIcon = IconWrapper(TrashSvg);
export const SuitcaseIcon = IconWrapper(SuitcaseSvg);
export const PaperPlusIcon = IconWrapper(PaperPlusSvg);
export const TagIcon = IconWrapper(TagSvg);
export const AddModalIcon = IconWrapper(AddModalSvg);
export const CheckIcon = IconWrapper(CheckSvg);
export const TagFillIcon = IconWrapper(TagFillSvg);
export const SuitcaseFillIcon = IconWrapper(SuitcaseFillSvg);
export const XIcon = IconWrapper(XSvg);
export const ArrowLeftIcon = IconWrapper(ArrowLeftSvg);
export const SettingsWhiteIcon = IconWrapper(SettingsWhiteSvg);
export const NotificationIcon = IconWrapper(NotificationSvg);
export const TimerCircleIcon = IconWrapper(TimerCircleSvg);
export const CalendarIcon = IconWrapper(CalendarSvg);
export const FlagIcon = IconWrapper(FlagSvg);
export const PomodoroIcon = IconWrapper(PomodoroSvg);
export const RepeatIcon = IconWrapper(RepeatSvg);
export const ArrowRightIcon = IconWrapper(ArrowRightSvg);
export const InfinityIcon = IconWrapper(InfinitySvg);
export const CircleEmptyIcon = IconWrapper(CircleEmptySvg);
export const CircleCheckmarkIcon = IconWrapper(CircleCheckmarkSvg);
export const HourGlassIcon = IconWrapper(HourGlassSvg);
export const GoogleIcon = IconWrapper(GoogleSvg);
export const FacebookIcon = IconWrapper(FacebookSvg);
export const EyeOffIcon = IconWrapper(EyeOffSvg);
export const EyeIcon = IconWrapper(EyeSvg);
export const EmailIcon = IconWrapper(EmailSvg);
export const DangerCircleIcon = IconWrapper(DangerCircleSvg);
export const CancelIcon = IconWrapper(CancelSvg);
export const CalendarFillIcon = IconWrapper(CalendarFillSvg);
export const ArrowRightVectorIcon = IconWrapper(ArrowRightVectorSvg);
export const ArrowDownIcon = IconWrapper(ArrowDownSvg);
export const AppleIcon = IconWrapper(AppleSvg);
export const PlusIcon = IconWrapper(PlusSvg);
export const FileUploadIcon = IconWrapper(FileUploadSvg);
export const FileIcon = IconWrapper(FileSvg);
